### ISSUE TITLE
`bootstrap.py` does not install backend requirements

### ISSUE THREAD

**Issue by lukavdplas** [UUDigitalHumanitieslab/readit-interface#570]
Running `yarn install-back` (e.g. by running bootstrap.py) does not install the packages in `backend/requirements.txt`. Looks like it installs `functional-tests/requirements.txt` instead?

**Comment by jgonggrijp** [comment]
That is very surprising. Did you run that command from the project root? What is telling you the backend requirements aren't installed? We can have a screen sharing call if that helps.

**Comment by lukavdplas** [comment]
Correction, this is not a problem with install-back but with the bootstrap script. My reproduction:

<pre><font color="#4E9A06"><b>luka@KIM</b></font>:<font color="#3465A4"><b>~/Documents/read-it/readit-interface</b></font>$ python3 bootstrap.py
virtualenv [.env]: .env-test
virtualenv_command [virtualenv .env-test --prompt=&quot;(readit) &quot;]: 
Create the virtualenv... success.
Install pip-tools... success.
Install the backend requirements... success.
Install the functional test requirements... success.
Install the frontend packages... success.
psql_command [psql]: 
Create the database... success.
Run the initial migrations... failed (1).
Create origin-tracking master branch... failed (128).

Please read bootstrap.log for information on failed commands.

Almost ready to go! Just a couple more commands to run:
source .env-test/bin/activate
yarn django migrate
yarn django rdfmigrate
yarn django createsuperuser
git branch --track master origin/master
git flow init -d
yarn start
<font color="#4E9A06"><b>luka@KIM</b></font>:<font color="#3465A4"><b>~/Documents/read-it/readit-interface</b></font>$ source .env-test/bin/activate
(readit) <font color="#4E9A06"><b>luka@KIM</b></font>:<font color="#3465A4"><b>~/Documents/read-it/readit-interface</b></font>$ pip list
Package          Version
---------------- ---------
async-generator  1.10
attrs            21.4.0
build            0.10.0
certifi          2019.6.16
cffi             1.15.0
click            8.1.3
cryptography     37.0.2
h11              0.13.0
idna             2.8
iniconfig        1.1.1
outcome          1.2.0
packaging        19.1
pip              23.0.1
pip-tools        6.12.2
pkg_resources    0.0.0
pluggy           0.13.1
py               1.11.0
pycparser        2.21
pyOpenSSL        22.0.0
pyparsing        2.4.2
pyproject_hooks  1.0.0
PySocks          1.7.1
pytest           7.1.1
selenium         4.3.0
setuptools       44.0.0
six              1.12.0
sniffio          1.2.0
sortedcontainers 2.4.0
tomli            2.0.1
trio             0.21.0
trio-websocket   0.9.2
urllib3          1.26.9
wheel            0.34.2
wsproto          1.1.0
</pre>

When I ran `yarn install-back` after this it worked fine. Looks like the problem is that the bootstrap script also runs `pip-sync` for the functional test requirements after installing the backend packages.

**Comment by lukavdplas** [comment]
Yes, if it's resolved elsewhere then no problem!
